In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
arr = np.array(42)

print(arr)

42


In [ ]:

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr[1])

2


In [ ]:
print(arr[2] + arr[3])

7


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  10


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [ ]:
print(arr[4:])

[5 6 7]


In [ ]:
print(arr[:4])

[1 2 3 4]


In [ ]:
print(arr[-3:-1])


[5 6]


In [ ]:
print(arr[1:5:2])

[2 4]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [ ]:
print(arr[0:2, 2])

[3 8]


In [ ]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32
